### ISSUE TITLE
Data quality checks gap analysis

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#13]
Need to identify the gaps between ALA's current suite of data quality tests and GBIF's.
The follow up to the work would be to implement any missing tests into pipelines, ideally supported in GBIF's core implementation.

A list of ALA's tests can be derived from here:

[ALA Assertion codes](https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/vocab/AssertionCodes.scala)

The GBIF pipeline equivalent is here:

[GBIF Occurrence issues](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/OccurrenceIssue.java)

 and 

[GBIF Name usage issues](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/NameUsageIssue.java)

**Comment by RobinaSanderson** [comment]
Hi @djtfmartin - Is the GBIF Fact or Measurement transform where they do their data quality checking, or is there another transform missing from our diagram: https://confluence.csiro.au/display/ALASD/Process+overview+and+issues?
I'm wondering if I should put in a dotted box on the diagram in the ALA space for data quality checks in case the outcome of this issue results in additional data quality checking. Otherwise, it can wait until we know one way or the other.

**Comment by djtfmartin** [comment]
Thanks @RobinaSanderson. The data quality checks are in various transforms (Location, Temporal, Taxonomy).

**Comment by RobinaSanderson** [comment]
Thanks, I see... Does it make sense to look at all the data quality checks as this one issue, or to split them up into separate issues for each transform if that is where they happen? Or do we need to do this task to get an overview of all the data quality work, and then have individual tasks for where we have to update/add to transforms?

**Comment by Tasilee** [comment]
I am wondering if we should put a lot of effort in when there was an undertaking some time ago from GBIF, ALA and iDigBio to implement TDWG TG2 Core Tests. That was previous administration admitted (John Donald at least). 

And BTW, I have a table somewhere with all the tests from various agencies that I could find. I will see if I can find it. This was my start point for the TG2 work.

**Comment by djtfmartin** [comment]
thanks @RobinaSanderson, i think separate tasks. We have tasks for Location #22  and Taxonomy #26 but we need separate task for Temporal (EventProcessor in biocache-store). We also need tasks for the functionality handled in TypeStatusProcessor, BasisOfRecordProcessor and the other processors. 

https://github.com/AtlasOfLivingAustralia/biocache-store/tree/master/src/main/scala/au/org/ala/biocache/processor

**Comment by RobinaSanderson** [comment]
Hi @djtfmartin I've created the following gap analysis issues:
EventProcessor - #55 
TypeStatusProcessor - #56 
BasisOfRecordProcessor - #57 
These are placeholders at the moment and will need more detail.

I will take a look at the link you gave above for further processes later. Sorry, I've got another piece of work to finish today.

**Comment by javier-molina** [comment]
This and #125 are related activities

**Comment by charvolant** [comment]
Assertion codes not used (set) in biocache-store and biocache-service

* BADLY_FORMED_ALTITUDE
* AMBIGUOUS_NAME
* PROCESSING_ERROR - DAOs check for this but it doesn't seem to be set anywhere
* MEDIA_REPRESENTATIVE
* MEDIA_UNREPRESENTATIVE

Assertion codes only used in biocache-service

* VERIFIED

**Comment by charvolant** [comment]
Things potentially missing from pipelines.

- [ ] Generic user assertion codes. It's unclear how or whether these should be implemented, since they're really part of the biocache-service and derived from a cassandra table. The LocationRecord has a hasGeospatialIssue flag on it but it is never set and no other record has a similar flag.
- [ ] COORDINATE_HABITAT_MISMATCH Believed to be deprecated
- [ ] DETECTED_OUTLIER Implemented with an outlier count in the index but no flag.
- [ ] COORDINATE_PRECISION_MISMATCH - see #285 
- [ ] SPECIES_OUTSIDE_EXPERT_RANGE - No expert range processing at present
- [ ] NAME_NOT_IN_NATIONAL_CHECKLISTS - Believed to be deprecated
- [ ] UNRECOGNISED_COLLECTION_CODE - Mapped by ALACollectionLookup but a not found is not flagged
- [ ] UNRECOGNISED_INSTITUTION_CODE - Mapped by ALACollectionLookup but a not found is not flagged
- [ ] INFERRED_DUPLICATE_RECORD - Detected by the clustering pipeline but not flagged
- [ ] RECORDED_BY_UNPARSABLE - Unparsable names are not flagged by CollectorNameParser

**Comment by javier-molina** [comment]
Everything in comment above 21 Apr has been addressed.
