### ISSUE TITLE
Exported DwCA for includes a associatedMedia value of 'original.jpeg'

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#159]
The export from Cassandra for 'dr1411` includes an associatedMedia field with the value 'original.jpeg'

https://biocache.ala.org.au/ws/occurrences/0082e681-2c8e-475e-97b4-6f496ede102d

This causes a minor issue in pipelines as the MultimediaTransform attempts to construct a URL from this value 'http://original.jpeg'. This results in 2 `Multimedia` objects associated with the `MultimediaRecord`. The first one is correct the second one is a blank Multimedia object with a `references` value of `http://original.jpeg`.

I think the fix here is to not export this value in the DwCAs as its not useful. Im not clear on the origin of it.

**Comment by muttcg** [comment]
One of the steps inside MultemediaTransforms interprets DwcTerm.associatedMedia core term, the interpreter uses [gbif uri parser](https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/UrlParser.java#L73)
Because that record contains `"associatedMedia": "original.jpeg"` interpreter converts into `http://original.jpeg`
This result is expected

**Comment by sadeghim** [comment]
Done
