### ISSUE TITLE
Migrate firstLoaded field stored in Cassandra

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#162]
This field is been populated by `biocache-store` and it shows the date when this record has been loaded into the system for first time.

**Comment by sadeghim** [comment]
@djtfmartin We need to to migrate this data across and have a mechanism in pipelines to persist this information. We may include this in the uuid avro file then it won't need loading a separate file and linking them against the records.

**Comment by peggynewman** [comment]
This is the default sort order of records in biocache.
We're considering at a data loading metrics report that uses this date with @CorinnaPaeper 
@djtfmartin is this a good idea? eg. how many records were loaded on x date.

**Comment by javier-molina** [comment]
This was part of #120 

TBC: It may be addressed as part of #14

**Comment by djtfmartin** [comment]
Of the 92,217,602 rows in the biocache, only 59,355,513 (64%) of records have a `firstLoaded` value.
I think this is mainly due to the fact the feature was only added some years after running this cassandra based biocache.

**Comment by djtfmartin** [comment]
@peggynewman I'm considering what we do for the blank values. One option is to fill in the blanks with the value `dateCreated` value in the collectory:

```
"dateCreated": "2015-02-12T04:03:42Z",
```

this would give the record the earliest possible entry date for the system, which will skew stats to particular days, but it will help to get stats for a more complete picture of the data in ALA. 

What do you think?

**Comment by peggynewman** [comment]
It's not the case that firstLoaded was only populated since the date the feature was added. There are plenty of records dated 2017-2019 that are blank. In the case of dr359, 7m records from these years would be given a first load date of 2010, so that's probably not great.  I'll send you a spreadsheet to have a look at.

From my sieve like memory (correct me if I'm wrong @sadeghim) we worked out that something happens when we do record deletes and reloads, and we attempt to  rowkey mappings to retain UUIDs, that messes this date up.

we were looking at the code here: 
https://github.com/AtlasOfLivingAustralia/biocache-store/blob/cd53dbf898d13edb4e7911697e70e59609ec1763/src/main/scala/au/org/ala/biocache/load/DataLoader.scala#L219
 
Another option might be to use last loaded date? Are most of them there or have I got that wrong with this query:
https://biocache.ala.org.au/occurrences/search?q=-first_loaded_date:[*%20TO%20*]&fq=last_load_date:[*%20TO%20*]

**Comment by djtfmartin** [comment]
Merged.
