### ISSUE TITLE
Break up biocache services in multiple microservices

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#19]
Work was started on a experimental branch of biocache-service to allow for retrieving the full record details. This work need further implementation and further testing.

In addition, It may be beneficial in the medium to long term to split biocache service into separate micro services to help partition different functions with a view to deprecate functionality in favour of GBIF tools.

Possible micro service splits:

* Annotations
* Downloads
* Mapping
* Search services
* Spatial utilities (scatterplot, etc)

**Comment by nickdos** [comment]
Added "Spatial utlities"

**Comment by javier-molina** [comment]
@nickdos, @djtfmartin is this something that needs to be done as part of LA pipelines Minimal Viable Product?

In my view this sounds like a good to have but not a must for Stage 1, I would argue that the proposed break up is a good starting point for an in depth gap analysis for when we get to Stage 3 but I'm happy to hear otherwise.

**Comment by djtfmartin** [comment]
I don't think this required for MVP.
