### ISSUE TITLE
dr2287 - duplicate keys in BRI AVH data

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#206]

**Comment by peggynewman** [comment]
@nielsklazenga can you check for duplicates in this data resource?

**Comment by nielsklazenga** [comment]
I do not know about duplicates, but there are 163 records that were not in the data set that I last uploaded:

https://avh.ala.org.au/occurrences/search?q=*%3A*&qc=data_hub_uid%3Adh9&fq=data_resource_uid%3A%22dr2287%22&fq=last_load_date:[*%20TO%202020-06-01T00:00:00Z]#tab_recordsView

One of these has an image, so I do not just want to delete them. I will check tomorrow if I can find a new occurrence record I can attach it to. If not, I will do a download and send to BRI to sort out and delete the records afterwards.

**Comment by nielsklazenga** [comment]
From discussion in the Backlog Refinement meeting just now, I understand that these are multiple UUIDs for the same row key. So I need to do the following:

-[ ] Link the one image in the query above to the right occurrence record
-[ ] Remove the duplicate occurrence records (as per the query above)
-[ ] Remove duplicates from occ_uuid table in Cassandra
-[ ] Get back to @sadeghim so he can check if everything is okay now.

**Comment by nielsklazenga** [comment]
Hi @sadeghim , the `occ.occ_uuid` table has a lot of junk for `dr2287`. There are no duplicates among the row keys that are still in use.

Shall I just clean up the junk, both from the row key and occurrences tables?

**Comment by sadeghim** [comment]
@nielsklazenga I now deleted the junk records from `occ_uuid` table. 557,095 records, almost same number as we have now in the biocache.

**Comment by nielsklazenga** [comment]
Thanks @sadeghim , anything you still need me to do?

**Comment by sadeghim** [comment]
@nielsklazenga I see that there are still some records having duplicate `catalogNumber`s.
I don't know which record s are redundant and should be deleted. Here is the list:
|rowkey                              |catalogNumber|
|------------------------------------|-------------|
|ba0b8340-3262-42da-b875-8cd5a64399be|BRI AQ0004888|
|830dffd0-33c2-4bc4-b9ed-7c997ae016c0|BRI AQ0004888|
|c9be99a4-6843-4581-ae8b-7d50770e13c7|BRI AQ0011330|
|79708dc6-4bb2-418c-b84d-8040f1b9a593|BRI AQ0011330|
|2cbea4aa-6ea8-4789-b5c7-03d51ac097b7|BRI AQ0038028|
|8d53f530-0ac5-4bf8-9284-bb2f8e07a1a2|BRI AQ0038028|
|997ea039-b7ec-47fe-bfbf-9040046a5526|BRI AQ0163055|
|68a5b13f-7109-4360-ad51-c16243a34e9c|BRI AQ0163055|
|5205979f-1da9-4afa-b1c4-5d521a021f91|BRI AQ0276842|
|2b1c4c6c-2702-4969-8259-29b6e337c480|BRI AQ0276842|
|927518d3-21b5-4814-a988-25156f19a164|BRI AQ0321506|
|7ea3a4d2-d563-409e-9c95-df0dad47a5d2|BRI AQ0321506|
|73786190-8f7c-43f6-ae93-2759874b34c3|BRI AQ0322553|
|43e76ac3-f64b-4f30-a41f-79730a4da0ed|BRI AQ0322553|
|c9866c78-c6eb-4040-9d9c-39e0ce34bf1e|BRI AQ0541402|
|3b24c844-a3fa-43fe-9801-01d336c6428a|BRI AQ0541402|
|87bb7a5e-96ed-4c9b-a8b4-590d10b95518|BRI AQ0543538|
|7facb3a0-527d-4c86-b9c4-35b84712dc76|BRI AQ0543538|
|ea0122cd-763e-4247-b987-7d27f07e7818|BRI AQ0645396|
|9c8b4444-dd4a-4143-8c1c-2e05cd7cd812|BRI AQ0645396|
|59f932ce-262c-4dc5-a7fa-970f29b5df2b|BRI AQ0753348|
|632a3330-d0ee-41e5-ab10-95b772963425|BRI AQ0753348|
|94545141-372d-4283-8bda-a954b3ec1a1a|BRI AQ0761437|
|98e73752-2689-4b4d-8582-2dee53f0c379|BRI AQ0761437|
|3156728c-17b0-465e-b470-13e5b4cee36c|BRI AQ0775292|
|1cc79726-2eec-4f35-86ba-0e017bacf6c3|BRI AQ0775292|
|42a46b61-738a-4d89-a02e-6acdf21fdc71|BRI AQ0826866|
|7438bf61-1781-41a2-8b24-f62f78296e8c|BRI AQ0826866|
|8205c100-485c-45c7-95d6-7792b3c3d310|BRI AQ0907629|
|d71c9674-aab4-47eb-a54a-846425f84bf9|BRI AQ0907629|

**Comment by nielsklazenga** [comment]
Hi @sadeghim, these are the row keys that can be deleted:

Record ID | Catalogue Number
-|-
ba0b8340-3262-42da-b875-8cd5a64399be | BRI AQ0004888
c9be99a4-6843-4581-ae8b-7d50770e13c7 | BRI AQ0011330
8d53f530-0ac5-4bf8-9284-bb2f8e07a1a2 | BRI AQ0038028
997ea039-b7ec-47fe-bfbf-9040046a5526 | BRI AQ0163055
5205979f-1da9-4afa-b1c4-5d521a021f91 | BRI AQ0276842
7ea3a4d2-d563-409e-9c95-df0dad47a5d2 | BRI AQ0321506
43e76ac3-f64b-4f30-a41f-79730a4da0ed | BRI AQ0322553
3b24c844-a3fa-43fe-9801-01d336c6428a | BRI AQ0541402
9c8b4444-dd4a-4143-8c1c-2e05cd7cd812 | BRI AQ0645396
632a3330-d0ee-41e5-ab10-95b772963425 | BRI AQ0753348
94545141-372d-4283-8bda-a954b3ec1a1a | BRI AQ0761437
1cc79726-2eec-4f35-86ba-0e017bacf6c3 | BRI AQ0775292
7438bf61-1781-41a2-8b24-f62f78296e8c | BRI AQ0826866
d71c9674-aab4-47eb-a54a-846425f84bf9 | BRI AQ0907629

I have just deleted the occurrences.

I was unsuccessful in removing the entries from the `occ_uuid` table, because it did not let me just delete one of the uuids. I think I can do it by deleting all entries and putting the ones that should not be deleted back in, which I can try next week, but you can probably do it way faster than I can.

**Comment by sadeghim** [comment]
@nielsklazenga , All of the above records are deleted now.
But here is another duplicate. Could you please have a look?

|rowkey                              |catalogNumber|
|------------------------------------|-------------|
|7facb3a0-527d-4c86-b9c4-35b84712dc76|BRI AQ0543538|
|87bb7a5e-96ed-4c9b-a8b4-590d10b95518|BRI AQ0543538|

**Comment by nielsklazenga** [comment]
Hi @sadeghim , I have deleted `7facb3a0-527d-4c86-b9c4-35b84712dc76` for the occurrence table.

**Comment by sadeghim** [comment]
OK, thanks.
Now this one is also cleaned up from `occ.occ_uuid`:
`DELETE FROM occ.occ_uuid where rowkey='dr2287|BRI|BRI AQ0543538';`
