### ISSUE TITLE
ALA export to GBIF - use Avro files?

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#23]
This is a question (of scope). Should we create a task to use the Avro files as the basis for our regular export to GBIF?

Any data that is shared with GBIF will be going through the SDS before it gets to GBIF as it does in current production. 

So this is a question about whether we can produce something in AVRO that GBIF can consume with the data having gone through the SDS, or produce the DwCAs for GBIF to consume as we currently do in biocache-store.

**Comment by timrobertson100** [comment]
Interesting idea. 

Rather than jumping into the format, we might want to consider if GBIF.org should rely on ALA based interpretations or use the verbatim (in which case the `ExtendedRecord` Avro format would be ideal). 

A downside is that today GBIF are able to point at a file which is to a globally recognised data format as the origin for the data arriving in GBIF.org.

**Comment by djtfmartin** [comment]
Pull request ready for review

https://github.com/gbif/pipelines/pull/520
