### ISSUE TITLE
Data management use-cases for data loading and troubleshooting with Cassandra 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#24]
@sadeghim mentioned that he regularly runs CQL queries across Cassandra when preparing data updates and when trying to troubleshoot issues with new data loads, etc.

**Task**: collect a list of these queries and categorise them into common use-cases.  

We then need to find ways of working with Avro files to cover the same use cases. This might might be utility scripts or using command line tools, etc.

If a coding solution is required, then create an issue for it, otherwise close with link to utility or equiv. solution.

**Comment by timrobertson100** [comment]
GBIF use Hive HQL for this because it fits well for our data warehouse. Our pipeline implementation moves latest data into the hive warehouse, using zookeeper for locks/barriers to orchestrate that.

Assuming you bring up some kind of Spark cluster, Spark-sql might be an option to consider without the need to bring in more infrastructure.

**Comment by djtfmartin** [comment]
After some initial testing, Spark-ql seems to mean some basic needs and gives a much richer query tool than CQL offered.

Example - using `spark-shell` with Spark-QL it is easy to retrieve distinct values from a single dataset or across all datasets just working with AVRO files. More complex queries with joins are also possible.

**Comment by djtfmartin** [comment]
I believe this issue can be closed as we have identified tools that can be used and tested `Spark-ql` on the cluster and locally.
