### ISSUE TITLE
lifeStage vocabulary isnt currently in use

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#259]
GBIF had added functionality to include vocabulary lookups for `lifeStage`. We need to add this to our interpretation pipeline.

see https://github.com/gbif/pipelines/issues/488

**Comment by djtfmartin** [comment]
Done on this branch: https://github.com/gbif/pipelines/pull/494

**Comment by djtfmartin** [comment]
Awaiting review in this PR: https://github.com/gbif/pipelines/pull/494

**Comment by djtfmartin** [comment]
reviewed and merged

**Comment by RobinaSanderson** [comment]
Hi @djtfmartin - Is this a strict vocabulary or will other values be accepted? If strict, will past records be changed? Just wondering how it will affect end users

**Comment by djtfmartin** [comment]
It is strict in the sense on non-fuzzy matching, but we can work with GBIF to add more values to the vocab through their vocab tools.

**Comment by RobinaSanderson** [comment]
Thanks @djtfmartin 

So looking at this:https://www.gbif.org/article/5i3CQEZ6DuWiycgMaaakCo/gbif-infrastructure-data-processing am I right in thinking we will look at whatever value is in the field and if it matches one in the dictionary, it is processed (indexed?). Otherwise the supplied value is kept but not indexed?

Prod has 561 Adult occurrences and everything else is unsupplied whereas quoll has 782,154 adult occurrences and a lot more choices so looks like a pretty useful change.
