### ISSUE TITLE
Setup monitoring for Spark and SOLR clusters

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#29]
Just a placeholder issue to ensure we track monitoring setup for new environments.

**Comment by djtfmartin** [comment]
Zabbix in places thanks to the ansible setup scripts. Some preliminary dashboards created.

**Comment by ansell** [comment]
ELK monitoring (filebeat only currently) is also in place for the system log files and SOLR log files (5 days retention only on Solr log files, but longer on system log files). Can setup filebeat as necessary for any other log files that it should be processing.

Other beats can be activated as necessary, but we can't support the other beats on all ALA servers due to capacity issues in ELK.

**Comment by djtfmartin** [comment]
Im not aware of anything outstanding to be done here. Moving to done.
