### ISSUE TITLE
fix travis build

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#294]
The travis build needs to be fixed in order to perform deployments of biocache-service to quoll via ansible.

Need to:
 - [x] create docker images for Solr 8 with pipelines schema
 - [x] fix unit and integration tests
 - [x] test travis build

**Comment by djtfmartin** [comment]
cc @brucehyslop 

The build is now running with docker and integration tests on the `epic/pipelines/develop` branch.
It is working in travis and deploying to nexus.

I have temporarily added `@Ignore` annotations  and `FIXME` markers to some tests that will need to be addressed.

They include: 
- [ ] OccurrenceControllerTest.getRecordTest - a section of code related to logging
- [ ] OccurrenceControllerTest.taxaCountTest
- [ ] FilterQueryParserTest
- [ ] DownloadServiceTest - This is breaking due to the need to have IndexDAO initialised (throwing NPEs)
- [ ] QidCacheTest

**Comment by brucehyslop** [comment]
integration tests fixed in AtlasOfLivingAustralia/biocache-service/pull/582
