### ISSUE TITLE
Improve sampling speed for all datasets

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#31]
The sampling process currently has 3 parts:

* Export lat/lng using beam pipelines to CSV
* Run sampling with java class which is using sampling.ala.org.au to retrieve values for a dataset, and same to CSV
* Generate a MapDB based sampling cache.

The sampling cache is then used in a readonly manner by the indexing process to pull in values for a lat/lng combination at indexing time.

This process works fine for per dataset level loading, but is inefficient for complete sampling and indexing jobs for all datasets.

Steps required:

 - [x] Produce a single export all lat longs pipeline to run on cluster
 - [ ] Produce a single sample cache for all lat lng
 - [ ] Use cache in indexing

**Comment by djtfmartin** [comment]
Single export for lat longs runs in **4 mins** (exporting 6 million points), compared to 120 minutes for separate jobs per dataset.

**Comment by djtfmartin** [comment]
Sampling currently takes 16 mins for dr2009. This is a 18.9 million record set with 180k points.
I believe this is adequate performance compared to current biocache. This issue can be closed and new issues raised for sampling as required.

**Comment by ansell** [comment]
This needs to be tested again on the new sampling server that has a different configuration to the previous server.

**Comment by javier-molina** [comment]
Thanks @ansell for bringing this to our attention.

Mahmoud mentioned the commission of the new server in one of our stand up meetings. At this stage I will leave it as closed as we prefer to create new tickets instead if there is a concern rather than re-opening previous tasks.

Performance will continue to be tackled and it is one of the risks I report on during the Project Steering Committee session. 

Sampling in particular continues to be tested indirectly, currently as part of #78
