### ISSUE TITLE
Spatial portal - layer information page

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#315]
Pipelines environment – little penguin - saved session: https://nectar-spatial-test.ala.org.au?ss=1619663986960
Production environment – little penguin - saved session: https://spatial.ala.org.au?ss=1619664082080

**Steps to recreate:**
1.	Open both environments in separate windows
2.	Click on the (i) icon next for the Eudyptula minor (Australia) layer in both windows

**Differences:**
1.	Number of occurrences – pipelines has 155541, production has 181610
2.	Data assertion chart – field names are being displayed rather than more user friendly labels
3.	Missing charts:
•	By collection – says loading but doesn’t display
•	By type status – says loading but doesn’t display
•	By state conservation status – says loading but doesn’t display
•	By decade – chart shown but no values display

**Issue in both production and test:**
Open the information page for a layer, close the information page, reopen the information page – the charts do not load.

**Comment by djtfmartin** [comment]
Most of the charts are fixed in https://github.com/AtlasOfLivingAustralia/biocache-service/pull/595

The difference in record counts are due to missing data covered[ in these issues](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues?q=is%3Aissue+is%3Aopen+label%3Adata-cleaning)

The not so friendly assertion names - I think this can only be fixed by updating i18n values in spatial-hub, so I think its something to fix in spatial-hub post release v1 of pipelines.
