### ISSUE TITLE
Collectory integration for a single dataset load

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#351]
Pipelines expects a data resource to have a DwCA available in HDFS in a specific directory `hdfs://.../data-exports` so it can be loaded through pipelines, starting with the initial step `la-pipelines dwca-avro dr123`

What we need is some logic implemented by the DM team to transfer the DwCA archive to the correct directory.

In the short term, this will likely be done with the following steps:

1) A lookup to collectory using the data resource web service `/ws/dataResource/dr123`
1) Parse supplied JSON, and validate that this resource is available in DwCA format (as opposed to DwC CSV)
1) Retrieve the URL for the DwCA archive from the connection parameters
1) Download the archive
1) Transfer to HDFS directory

cc @peggynewman @sadeghim

**Comment by peggynewman** [comment]
This will have to mimic biocache-store if the connection.parameter file url is uploads server - take the most recent file.
The script will need to authenticate to uploads as well.

The script should probably handle both csv and dwca at this stage because some of the csvs will be passed onto the script that converts csv to dwca.

**Comment by javier-molina** [comment]
Issue moved to [AtlasOfLivingAustralia/data-management #705](https://github.com/AtlasOfLivingAustralia/data-management/issues/705) via [**ZenHub**](https://www.zenhub.com/)
