### ISSUE TITLE
Different total occurrences of Eucalyptus gunnii  in Tasmania  from Biocache-ws-test and biocache prod

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#380]
Not sure if it is caused by different datasets used by test / prod server

Occurrences of Eucalyptus gunnii  in Tasmania from Biocache-ws-test is 402,
but Biocache prod returns 1676

Here is the two links, 
https://biocache-ws-test.ala.org.au/ws/occurrences/search?&facet=off&pageSize=0&q=qid:1622081158503

https://biocache-ws.ala.org.au/ws/occurrences/search?facet=false&pageSize=0&q=qid:1622158243804

**Comment by javier-molina** [comment]
Thanks @qifeng-bai 

Test has less records than prod.

See first entry on https://confluence.csiro.au/display/CIU/Communicating+changes+to+users for details.

If you can confirm that the missing records belong to the listed DR listed in the link below then that's the reason otherwise you can try to test with a particular DR on test and prod, if number of records are substantially different for that scenario then we need to do further investigation.

**Comment by qifeng-bai** [comment]
https://biocache-ws-test.ala.org.au/ws/occurrences/search?facet=off&pageSize=0&q=qid:1622173760375
https://biocache.ala.org.au/ws/webportal/params/details/1622173855042

only 16 difference
