### ISSUE TITLE
old raw_basis_of_record not mapping to new raw_basisOfRecord

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/la-pipelines#385]
- works https://biocache-test.ala.org.au/ws/occurrences/search?q=raw_basisOfRecord:HUMAN_OBSERVATION
- does not but should work https://biocache-test.ala.org.au/ws/occurrences/search?q=raw_basis_of_record:HUMAN_OBSERVATION

Wondering if all other raw_camelCase fields absent from the mapping file are failing. `raw_data_generalizations` and `raw_associated_references` do not translate but single word fields appear to work `raw_country`, `raw_class`, `raw_continent`.

**Comment by javier-molina** [comment]
I think this is in @brucehyslop domain

**Comment by brucehyslop** [comment]
I've copied the latest mapping config from the biocache-service project into ansible `biocache-service` role. See branch https://github.com/AtlasOfLivingAustralia/ala-install/tree/27_pipelines_spark_hadoop

The next release should use the updated config.

**Comment by brucehyslop** [comment]
The field naming convention for unprocessed fields in pipelines is to use the un-prefixed field to store these values. Therefore for fields that are no longer processed in pipelines there will not be a `raw_` field. 

Should we provide a field mapping for search in so that legacy _raw_ fields are mapped to their un-prefixed version?

 - [ ] `associated_references`
  no processed values in pipelines no `raw_associatedReferences` field

 - [ ] `data_generalizations`
   is processed from raw value in pipelines 
  `raw_dataGeneralizations`: 1,517,791 records , `dataGeneralizations`: 118,980 records
  added new mapping `raw_data_generalizations` ->  `raw_dataGeneralizations`

 - [ ]  `establishment_means `
  is processing from raw value in pipelines 
  `raw_establishmentMeans`: 2,711,949 records, `establishmentMeans`: 894,861 records
  added new mapping `raw_establishment_means` -> `raw_establishmentMeans`

 - [ ] `raw_geo_validation_status`
  no equivalent field in pipelines

 - [ ] `raw_identification_qualifier`
  no processed values in pipelines no `raw_identificiationQualifier` field

 - [ ] `raw_identification_references `
  no processed values in pipelines no `raw_identificationReferences` field

 - [ ] `raw_identified_date`
  is processing from raw value in pipelines 
  `raw_dateIdentified`: 954,064 records
  `dateIdentified`: 706,485 records
  added new mapping `raw_identified_date` -> `raw_dateIdentified`

 - [ ] `raw_information_withheld `
   is processing from raw value in pipelines 
  `raw_informationWithheld`: 1,565,764 records
  `informationWithheld`: 16,725 records
   added new mapping `raw_information_withheld` ->`raw_informationWithheld`

**Comment by brucehyslop** [comment]
Added new field mappings 

 - `raw_abcd_identification_qualifier` -> **deprecated**
- `raw_associated_references` -> `associatedReferences`
- `raw_datum` -> `raw_geodeticDatum`
- `raw_duplicate_record` -> `isDuplicateOf`
- `raw_easting` -> `easting`
- `raw_geo_validation_status` -> **deprecated**
- `raw_georeference_protocol` -> `georeferenceProtocol`
- `raw_georeference_remarks` -> `georeferenceRemarks`
- `raw_georeference_sources` -> `georeferenceSources`
- `raw_georeferenced_by` -> `georeferencedBy`
- `raw_habitat` -> `habitat`
- `raw_ibra` -> `cl1048`
- `raw_identification_qualifier` -> `identificationQualifier`
- `raw_identification_references` -> `identificationReferences`
- `raw_images` -> `imageIDs`
- `raw_institution_id` -> `raw_institutionUid`
- `raw_name` -> **deprecated**
- `raw_name_according_to` -> `nameAccordingTo`
- `raw_nomenclatural_code` -> `nomenclaturalCode`
- `raw_northing` -> `northing`

**Comment by brucehyslop** [comment]
rerun field mapping analysis the following solr fields are in current prod but do now have a pipelines for or a mapping defined:

```
data_hub
last_user_assertion_date
min_elevation_d_rng
pest_flag
species_habitats
user_quality_assertion
```
 Note `species_habitats` has previously had a mapping to `speciesHabitats` however the field is not longer in pipelines.

**Comment by nickdos** [comment]
https://biocache-test.ala.org.au/ws/occurrences/search?q=raw_basis_of_record:HUMAN_OBSERVATION gives expected result ✅
