### ISSUE TITLE
Downloads are missing custom license information from Collectory

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#398]
E.g. compare these 2 downloads from prod and test:

https://doi.ala.org.au/doi/10.26197/ala.c88422f1-8329-4149-b767-21db39ea2da5
https://doi-test.ala.org.au/doi/10.80416/ala.6228c84c-5547-4d25-ab22-5ea5222bbfc6

- [ ] Counts are similar (97 vs 95) but the test version has **empty values for `Licence`** metadata entry as well as the **`Licence` column** in the `datasets` table. 

- [ ] Also note the number of rows in the 2 tables are quite different: **38 vs 24** (prod vs test). This suggests we are not getting the correct breakdowns from Collectory or similar.

-  [ ] I also see this error in the biocache-service logs:

```
[biocachedownload-pool-500000-RECORDS_INDEX-0] ERROR au.org.ala.biocache.service.DownloadService  (DownloadService.java:987) - A null record was returned from the collectory citation service.
```

- [ ] Looking at the `citations.csv` file from the downloads, I can see differences:

```
Tasmanian   Herbarium, Tasmanian Museum and Art Gallery. PO Box 5058, UTAS LPO, Sandy Bay   7005, Tasmania, Australia. https://www.tmag.tas.gov.au/
--
Records provided by   Tasmanian Museum and Art Gallery, accessed through ALA website.
```

EDIT: Check the API key is correct for collectory in biocache-service, as first go.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/627

**Comment by nickdos** [comment]
I'm not sure that is related @adam-collins.

I suspected we're missing the API key in biocache-service config, as the logs show:

> A null record was returned from the collectory citation service.

and citation data is missing, so seems logical that the service is to blame.

**Comment by adam-collins** [comment]
This fixes the issue.

- dataResourceUid is requested twice in the fl term supplied to SOLR.
- In current biocache-service the additional dataResourceUid is ignored.
- In the pipelines biocache-service the flMapping within FieldMappedQueryResponse has 2 entries for dataResourceUid. This results in the SolrDocument containing 2 values for dataResourceUid. e.g. "[dr123, dr123]" instead of "dr123".
- uidStats contains references and counts for collectory entries in the download. These counts are incremented by the method SearchDAOImpl.incrementCount. 
- incrementCount uses the method SolrDocument.getFieldValue(dataResourceUid) that returns a list for multivalued entries. 
- Since field mapping calls SolrDocment.addField(dataResourceUid, dr123) twice, this results in the incrementCount method using [dr123,dr123] as the key (collectory id) for all associated counts instead of only dr123.
- DownloadService.getCitations sends a request for citation information in the collectory for all collectory ids in the uidStats map. This service defaults to https://collections.ala.org.au/ws/citations
- When the collections id appears as the string "[dr123,dr123]" this above webservice returns NULL. So no information is avialable.
- Note that a request for the correct string "dr123" returns a non-null result.
- This is validated first by observing that https://doi-test.ala.org.au/doi/10.80416/ala.6228c84c-5547-4d25-ab22-5ea5222bbfc6;jsessionid=42C4CB20E92A7959D05DDC3B97E0FF3F contains no collectory ids that begin with 'dr', that is, a dataResourceUid.
- The second validation is done by observing that there is only licence information for 'dr' collectory ids in https://doi.ala.org.au/doi/10.26197/ala.c88422f1-8329-4149-b767-21db39ea2da5;jsessionid=EF9D423265BBBCB68987C39EA433757C

Therefore, removing the duplicate SolrDocument entry for dataResourceUid results in the correct value being sent to the collectory webservice and the citation information containing the licence text (only appearing for dataResourceIds) is returned (appears as 'rights' in the response from the webservice and is mapped to 'licence').

**Comment by djtfmartin** [comment]
Retested and it LGTM.

**Comment by nickdos** [comment]
Tested ✅  data resource/collection/inst counts are now matching with prod.
