### ISSUE TITLE
Dynamic properties are not available for rowKeys

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#443]
Values in the dynamicProperties field that are used by a dataset to produce a unique key will always be null. As an example, dr1089 uses subspeciescode as a unique identifier term. This leads to duplicate keys.

Current work-around, rebuild another key field to contain the extra data.

**Comment by peggynewman** [comment]
The data team should work with data providers to specify that unique keys should always at the very least be darwin core terms and thus not hidden in dynamicProperties.

I would prefer we only worked with occurrenceID, but we have the legacy Darwin Core triple, institutionCode|collectionCode|catalogNumber all through collections records, which is fine. But we should steer any future data providers away from using a series of composite keys that represents the record uniqueness as our 'unique keys'.

This seems like a semantic problem to me. In our `DwCtermsthatuniquelyidentifyarecord` field in the collectory, we really want a primary key, not a unique key. If any of the values in the unique key changes (eg esp taxon), then we can't update the key without making a mess.

While it's good practice to know exactly which is the minimum set of fields that makes a record unique, data providers should manage and provide us with a primary key so that we can maintain consistency.

I don't think we should build a workaround for this.

**Comment by djtfmartin** [comment]
I agree @peggynewman

**Comment by djtfmartin** [comment]
Can this be closed ?

**Comment by charvolant** [comment]
Works for me.
