### ISSUE TITLE
DQ filter help points to old documentation

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#456]
Issue is with links to field information assertions are OK:
* the filters using old field names that are mapped to new names, point to the old wiki pages, for example the spatiallyValid filter links to the geospatial_kosher wiki page, the filter using duplicateStatus links to the duplicate_status wiki page
* new filters need to have a link created to the new pages, for example decimalLatitude 

Fields which have been changed and need to have links redirected:
•	spatiallyValid  - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/spatiallyValid
•	duplicateStatus  -  https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/duplicateStatus
•	coordinateUncertaintyInMeters  - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/coordinateUncertaintyInMeters
•	userAssertions - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/userAssertions
•	outlierLayerCount - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/outlierLayerCount
•	basisOfRecord - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/basisOfRecord
•	occurrenceStatus - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/occurrenceStatus
•	 year - doesn't need changing as the name remains the same
•	license - doesn't need changing as the name remains the same
•	IsDuplicateOf - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/isDuplicateOf
•	taxonomicIssue - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/taxonomicIssue
•	decimalLatitude - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/decimalLatitude
•	decimalLongitude - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/decimalLongitude
•	contentTypes - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/contentTypes
•	establishmentMeans - https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/establishmentMeans

The messages.properties file connects the user interface with the github wiki page https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2c013e15d88350671ced5cabfe6781695d816fb9/src/main/webapp/WEB-INF/messages.properties

as explained in https://confluence.csiro.au/display/ALASD/Field+and+assertions+metadata+architecture+and+editing

Steps to replicate issue
1. Open a search results page
2. Have the ALA general data profile displayed
3. Click on the information icon for the location uncertainty filter category
![image](https://user-images.githubusercontent.com/23368496/123751019-964d3d00-d8fa-11eb-9c1c-8343b822fefd.png)
4. Click on the further information link for coordinateUncertaintyInMetres
![image](https://user-images.githubusercontent.com/23368496/123751281-e9bf8b00-d8fa-11eb-8ab8-3ada36ef1ca1.png)

Expected behaviour
Wiki page for coordinateUncertaintyInMetres will open https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/coordinateUncertaintyInMetres

Actual behaviour
Wiki page for coordinate_uncertainty will open https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/coordinate_uncertainty

Hi @brucehyslop, please add anything I've missed.

**Comment by javier-molina** [comment]
I'm testing this

**Comment by javier-molina** [comment]
@brucehyslop I spotted these 3 issues below

Wrong url
![Screen Shot 2021-07-14 at 12 07 17 pm](https://user-images.githubusercontent.com/8326394/125551787-78d02298-4cf2-41a8-ac87-3cd071fa8f61.png)

and two information pages without links, possibly because the record count zero in test and might as well be an existing bug

![Screen Shot 2021-07-14 at 12 37 17 pm](https://user-images.githubusercontent.com/8326394/125552247-8fee7f96-dc6f-4d64-b9fd-5cb945a84234.png)

![Screen Shot 2021-07-14 at 12 36 51 pm](https://user-images.githubusercontent.com/8326394/125552258-7e7b59a9-df83-4bdf-9f19-1f86a0cbfdf1.png)

**Comment by brucehyslop** [comment]
The issue with the links for the:

| **Filter description**                                         | **Filter value**                | **Further information** |
|------------------------------------------------------------|-----------------------------|---------------------|
| Exclude all records where outlier layer count is 3 or more | -outlierLayerCount:[3 TO *] |                     |

| **Filter description**                                   | **Filter value**         | **Further information** |
|------------------------------------------------------|-----------------------|---------------------|
| Exclude all records with unresolved user assertions  | -userAssertions:50001 |                     |
| Exclude all records with unconfirmed user assertions | -userAssertions:50005 |                     |

Are both due to there being a small number of records with `outlierLayerCount` and `userAssertions`. The `index/fields` service is used to return the link info however this service retrieves the data from solr using the luke (Lucene Index browser) which only accessed a single shard. The the shared does not have any records containing the field it is not returned.

The biocache-service `index/fields` could be modified to merge the solr schema with luke data, this would ensure all fields defined in the schema are returned.

**Comment by brucehyslop** [comment]
There is an inconsistency with the way the links are derived between the full "Data Profile" info dialog and the info for each Filter.

The links for the full "Data Profile" filter section:
| **Filter description**                                                                                  | **Filter value**                                      | **Further information** |
|-----------------------------------------------------------------------------------------------------|---------------------------------------------------|---------------------|
| Exclude all records with an assertion of the occurence is cultivated or escaped from captivity      | -establishmentMeans:"MANAGED"                     |                     |
| Exclude all records with an assertion of latitude value provided is zero                            | -decimalLatitude:0                                | Link                |
| Exclude all records with an assertion of longitude value provided is zero                           | -decimalLongitude:0                               |                     |
| Exclude all records with an assertion of latitude and longitude have been transposed                | -assertions:"PRESUMED_SWAPPED_COORDINATE"         | Link                |
| Exclude all records with an assertion of coordinates are the exact centre of the state or territory | -assertions:"COORDINATES_CENTRE_OF_STATEPROVINCE" | Link                |
| Exclude all records with an assertion of coordinates are the exact centre of the country            | -assertions:"COORDINATES_CENTRE_OF_COUNTRY"       | Link                |

Has missing links because the `biocache-service` `index/fields` service does not handle a field list that contains numeric fields (see #481)

**Comment by brucehyslop** [comment]
issues related to DQ links covered in #419 and #481
