### ISSUE TITLE
sensitive values not coming in downloads

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#468]
Reported by Nick:

A user who has "sensitive" access to downloads and they are saying they no longer see the ungeneralised values in "legacy" format downloads.

`Longitude – ungeneralised, Latitude – ungeneralised, Locality – sensitive, Event date – sensitive or Grid reference – sensitive` are missing

**Comment by javier-molina** [comment]
From Adam:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/eb733bfe174283cd38[…]95/src/main/java/au/org/ala/biocache/util/DownloadCallable.java runs twice for sensitive downloads, that part is working. Need to double check that one of the queries has the sensitive fields requested.

This is also another point to look at:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/epic/pipelines/develop/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L847

**Comment by nickdos** [comment]
Would be good to create a functional test for this scenario using test Auth accounts with and without SDS roles.

**Comment by alexhuang091** [comment]
This issue is fixed. Just do a download with this [link ](https://biocache-dq-test.ala.org.au/occurrences/search?q=lsid:https://id.biodiversity.org.au/taxon/apni/51316871&disableAllQualityFilters=true&qualityProfile=ALA&fq=sensitive:"generalised"&fq=basis_of_record:"HUMAN_OBSERVATION"&fq=state:"New+South+Wales") you can see the data in `Longitude – ungeneralised` and `Latitude – ungeneralised`

Since `eventDate`, `locality` are not in `downloads.legacy.defaultFields` they and correspoding sensitive feilds won't be downloaded. @djtfmartin just need to decide if we need to download these fileds and update ansible script will be enough.

**Comment by nickdos** [comment]
Testing now...

**Comment by javier-molina** [comment]
Nick confirms fields names are not an issue related to this, everything else now works as expected.
