### ISSUE TITLE
upgrade ehcache integration with spring

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#503]
The current ehcache annotation support is using a 10 year old library `com.googlecode.ehcache-spring-annotations:ehcache-spring-annotations`

Spring 5 includes caching with a bridge to ehcache.

**Comment by javier-molina** [comment]
Is it safe to say this is implicitly tested by the fact that biocache-service is up and running in test?

**Comment by brucehyslop** [comment]
not necessarily. If the caching is not configured correctly biocache-service is likely to still function however would not be caching `@Cacheable` methods.

Since the validation of an apiKey is cached, this can be verified by making a request using with an apiKey defined and checking is subsequent requests trigger a request to the auth service. 

Clearing the caches (https://biocache-ws-test.ala.org.au/ws/cache/refresh) should revalidate the apiKey.

**Comment by javier-molina** [comment]
@nickdos, @adam-collins is that something you can do with appropriate access to server logs?

**Comment by javier-molina** [comment]
In yesterday's stand up meeting we discussed that testing this issue was difficult in production. Monitoring in Zabbix has not helped to trace whether caching is working in the test environment.

The caching has been tested successfully though in a local environment.  

It was agreed though this is low risk and we proceed with it. We need to monitor production after release for two potential scenarios:

- Values are not updated after being cached (no cache expiration)
- Increased calls to upstream services (no cache at all)
