### ISSUE TITLE
Create Test Plan

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#64]
How do we test every transformation?

Is index comparison with current prod for all fields and for all records what will probe that we are getting the same result?

Do we need to test at biocache-service in addition/instead of index?

How do we automate testing?

Will data volume put any constraint in time / processing resources?

**Comment by vjrj** [comment]
Some of the first things I did with our jenkins is to add some basic pre and post ingest testing in our jobs. See also the screenshots below. 
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Jenkins-For-Biocache-Store-And-Other-LA-Tasks#adding-tests-to-our-jobs
Please don't pay attention to the code. I added this because people in our team we doing this kind of comprobations manually or visually (like checking the number of occurrences ingested vs the occurrences in GBIF, etcetera). Previously, all our ingest jobs were finish ok, and now they show errors when that tests fail.

I was thinking now in some tests (or test suites) in the pipelines code that can we executed in production via some extra conditional arguments 
https://stackoverflow.com/questions/8168884/how-to-test-code-dependent-on-environment-variables-using-junit

- if the environment argument is passed to these tests (like a data resource number) the tests are executed using that variables. We can run this via scripts or some `--test|--skip-tests` argument in `la-pipelines` CLI and/or integrated with jenkins jobs.
- if not, the tests are passed via some default testing values (like `dr893`) for instance during the maven/build process, etcetera

**Comment by javier-molina** [comment]
Thanks @vjrj I was not aware of the work that you have done around tests in biocache store. I'm not sure though if your focus is around daily operation which I definitely welcome. We are thinking in functional testing that will allow us to validate that pipelines transforms/pipelines are equivalent to the current work biocache store is doing but definitely automation that allow us to repeat the tests is something that we are interested. 

I will make sure we continue the conversation. 

@sadeghim do you know if there is similar testing in ALA Jenkins to validate DR loads?

**Comment by vjrj** [comment]
I thinking mainly in daily operation, but also in reusing some tests code.
