### ISSUE TITLE
Implement COORDINATE_PRECISION_MISMATCH check

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#73]
GBIF interprets coordinatePrecision, but does not check if the coordinates match the given precision

Related assertion:
PRECISION_RANGE_MISMATCH
UNCERTAINTY_IN_PRECISION  (This is related to InterpretUncertainty)
COORDINATE_PRECISION_MISMATCH

Summary
1, Precision should be between 0..1. Out of this range will raise PRECISION_RANGE_MISMATCH

2, Compare the decimal place of cooridantePrecision and coordinates to determine if we should raise COORDINATE_PRECISION_MISMATCH
e.g.
  3.14159 matches the precision of 0.00001

Known questions:
1,  Does 3.141591 (6 decimals), match precision 0.00001 (5 decimals)?
    related issue: If the source coordinates is not WGS84, or use hms: 23hh23mm34ss, after projection, the output coordinates will always be the max decimal.  
  
2, Trailing zero issues.  If the supplied coordinates, for exmaple, 12.21000,  the 0 will be lost after it is converted to double/float.  Do we need to handle this case?

Related to #22
-------------------------------------------------------
If the source coordinates is not WGS84, after projection, the output coordinates will always be the max decimal.  
Do we need to truncate the decimal based on the source precision?
See issues:
https://github.com/AtlasOfLivingAustralia/biocache-store/issues/28
https://github.com/AtlasOfLivingAustralia/biocache-store/issues/107

**Comment by Tasilee** [comment]
This raises a general issue that I am sure @M-Nicholls is aware of: Convergence in GBIF, ALA and iDigBio on https://github.com/tdwg/bdq/issues?q=is%3Aissue+is%3Aopen+label%3ATest

Point being it is worth discussing one change instead of two. TG2 has gone through easily two person years of discussions and refinement on the (CORE) tests. For example, considering spatial, two of the TG2 team members just wrote this: http://mb.gbif.org/documents/doc-georeferencing-best-practices/en/georeferencing-best-practices.en.pdf

**Comment by javier-molina** [comment]
@qifeng-bai and @peggynewman to progress this discussion with GBIF.

**Comment by peggynewman** [comment]
More info in Confluence: https://confluence.csiro.au/display/CIU/DQ+Assertions+and+Mappings++-+Blocker+Resolution

**Comment by peggynewman** [comment]
From [georeferencing-best-practices](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#accuracy-error-bias-precision-false-precision-and-uncertainty):

**Precision:** We quantify precision as how specific a measurement should be to give consistent results. For example, a measuring device might give measurements to five decimal places (e.g., 3.14159), while repeated measurements of the same target with the same device are only consistent to four decimal places (e.g., 3.1416). We would say the precision is 0.0001 in the units of the measurement.

**Uncertainty**:  is a measure of how different an unknown true value might be from a value given. In georeferencing, we use uncertainty to refer to the maximum distance from a center coordinate of a georeference to the furthest point where the true location might be - a combination of all the possible sources of error given as a distance.

GBIF raises the issue COORDINATE_PRECISION_INVALID if between 1-45, but they're changing that to 0-1 (see Slack thread).
The ALA has PRECISION_RANGE_MISMATCH that would then map to that test.

It seems to me that if coordinatePrecision is set to 0.0001, and a location eg 36.14, then the assertion  COORDINATE_PRECISION_MISMATCH should be raised. 36.1400 wouldn't raise that assertion. Then we understand that the trailing zeros are important. 

The other assertion that TDWG BDQ recommends is UNCERTAINTY_IN_PRECISION, which indicates that it looks like coordinateUncertaintyInMeters (>0) and coordinatePrecision (0-1) are probably mixed up.

So that would make the final list:
COORDINATE_PRECISION_INVALID (between 0-1)
COORDINATE_PRECISION_MISMATCH (coordinates don't match the given precision)
UNCERTAINTY_IN_PRECISION (the values are probably swapped)

**Comment by peggynewman** [comment]
The ALA:COORDINATE_PRECISION_MISMATCH assertion is raised [if the number of decimal places in coordinatePrecision is not equal to the number in decimalLatitude/decimalLongitude](https://github.com/AtlasOfLivingAustralia/biocache-store/blob/5f2aef158db460f9e61febee2e6cf4ed0261861a/src/main/scala/au/org/ala/biocache/processor/LocationProcessor.scala#L598). There is likely still the issue raised in https://github.com/AtlasOfLivingAustralia/biocache-store/issues/28 about how real numbers in a system are represented without trailing zeros (eg decimalLatitude) in which case this assertion will be raised even if the data provider is doing the right thing.
Should the assertion only be raised if the number of decimal places in the coordinates is GREATER THAN the number in coordinatePrecision? That to me indicates that a user needs a warning. Whereas if there are less in the coordinates, you can check coordinatePrecision. 
@Tasilee any suggestions? Should this be left as is?

**Comment by qifeng-bai** [comment]
@peggynewman  
- ALA:UNCERTAINTY_IN_PRECISION (the values are probably swapped)
Precision is only a simple number, like 0.4, but uncertainty is very likely to have uom, like m/km
Do we need to  consider this situation, when we assume uncertainty in precision - which means the interpretation of precision needs to be rewritten as well

**Comment by peggynewman** [comment]
@qifeng-bai the uncertainty field is called coordinateUncertaintyInMeters. So the uom is meters.

Are you asking whether we really need the UNCERTAINTY_IN_PRECISION test? 

What do you mean by rewriting the interpretation of precision? The other test already checks that it's between 0 and 1.

**Comment by qifeng-bai** [comment]
@peggynewman  We convert it to UNCERTAINTY_IN_PRECISION, the source could be : 10km, 1000ft, 10-20km, something like that.  Anyway, I added extra codes to check if  the value of UNCERTAINTY_IN_PRECISION matches those pattern.

However, the decimal coordinates may have this format "31.210d",  we can correctly convert it to 31.21, but hard to detect 0 at end.  And the worst situation is GBIF pick up all digits in string when parsing coordinates,  for example  "32c. 3c1c" = 32.31
Do we also need to consider this situation when we check if precision_coordinates_match?

**Comment by peggynewman** [comment]
We've gotten off track here with UNCERTAINTY_IN_PRECISION, so problems related to that test have been moved out to another issue: https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/94 . This issue now only relates to COORDINATE_PRECISION_MISMATCH

**Comment by peggynewman** [comment]
Have email confirmation from @Tasilee that the TDWG BDQ group decided that the COORDINATE_PRECISION_MISMATCH test was not worth retaining and has not made it through to the set of final core tests at https://github.com/tdwg/bdq/projects/2 based on the principle that tests shouldn't produce false positives unless a strong point needs to be made. 
@qifeng-bai We can remove this test.

**Comment by javier-molina** [comment]
@qifeng-bai what is the difference between Deprecated and Cancelled/Suspended status in the spreadsheet? Suspended until when?

My understanding from Peggy's comment is that this assertion is going away so I would mark it as Deprecated.

Feel free to move this to the Done column once no more (analysis, I think) work is left

@RobinaSanderson do you think we need to document valid statuses and colors in the spreadsheet, in a similar way you did for the process diagram or is that over engineering?

**Comment by RobinaSanderson** [comment]
If we are agreed that the COORDINATE_PRECISION_MISMATCH is deprecated then I think the statuses are self explanatory.  

Is anyone confused by the test column or is it clear that we are only identifying tests if we use ALA assertions?

Just a couple of comments on the information in the spreadsheet:
* Not sure if all the implemented assertions have been marked as implemented at the moment there's only 2 listed, @qifeng-bai are they up-to-date?
* For GEODETIC_DATUM_ASSUMED_WGS84 the interpret we are using appears to be a GBIF one, we probably just need to say which one is being used.

**Comment by javier-molina** [comment]
Thanks @RobinaSanderson, happy with the self explanatory statuses.

I was not sure the test column referred to bstore tests, thanks for the clarification. 

I agree it is important to know if everything that has been implemented has been marked, this applies also to the other sheets in the spreadsheet document. 



> If we are agreed that the COORDINATE_PRECISION_MISMATCH is deprecated then I think the statuses are self explanatory.
> 
> Is anyone confused by the test column or is it clear that we are only identifying tests if we use ALA assertions?
> 
> Just a couple of comments on the information in the spreadsheet:
> 
> * Not sure if all the implemented assertions have been marked as implemented at the moment there's only 2 listed, @qifeng-bai are they up-to-date?
> * For GEODETIC_DATUM_ASSUMED_WGS84 the interpret we are using appears to be a GBIF one, we probably just need to say which one is being used.

**Comment by qifeng-bai** [comment]
@RobinaSanderson I deleted GBIF tests on purpose because I found it costs too much time to read though GBIF code to identify all tests.  We could trust GBIF has ready prepared all tests. So I just listed test for our assertion

**Comment by RobinaSanderson** [comment]
Yeah, I agree with not necessarily listing all the GBIF tests. We could call the column "ALA tests" but if everyone is clear on what's in there, then it can be left as is.
