### ISSUE TITLE
Evaluate performance of HDFS vs EFS on AWS

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#78]
Following on from the work in issue #65, we should test general performance of ingestion pipelines on **HDFS** and compare results with **EFS**.

**EFS** was used in the proof of concept mainly for convenience. **HDFS** is in use by GBIF in production. It should be possible to run all pipelines against either without code changes.

**Comment by djtfmartin** [comment]
Some timings from running the current processes on **EFS** and on **HDFS**. The indexing is with the full list of **534 layers** currently enabled in ALA production systems. The testing is with dataset **[dr2009](https://collections.ala.org.au/public/show/dr2009)** which contains **18.9 million records**.

Process name| Time taken EFS  | Time taken HDFS |
----------|--------|--------
DwCA to Verbatim |  TBA |  58 mins
Interpretation | 35mins | 13 mins
LatLng export  |  3 mins | 3 mins
Sampling | 4 mins | 5.5 mins
Sample AVRO | 9 mins | 2.5 mins 
UUID minting | 4mins | 2.5 mins
SOLR indexing | 34 mins |  29 mins
**Total time for complete ingestion ** | ** TBA ** |  **113.5 mins**

**Comment by timrobertson100** [comment]
I suspect the improvement here may come because the Verbatim Avro file created in the first stage is split into the 128MB (assuming defaults) blocks on HDFS which can then be read in parallel in the [HadoopFileSystem](https://github.com/apache/beam/blob/master/sdks/java/io/hadoop-file-system/src/main/java/org/apache/beam/sdk/io/hdfs/HadoopFileSystem.java#L189) whereas the EFS mount will read in sequence using the [LocalFileSystem](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/io/LocalFileSystem.java#L121).

**Comment by djtfmartin** [comment]
A complete load was ran of all processes. Here are some timings:

Process name |  Time taken HDFS |
----------|--------|--------
DwCA to Verbatim |   58 mins
Interpretation | 3.5 hrs
LatLng export  | 2 hrs
Sampling | 4hrs
Sample AVRO | 2 hrs
UUID minting | 2.5 hrs
SOLR indexing | 6 hrs
**Total time for complete ingestion of all data resource ** | 21 hrs

**Comment by djtfmartin** [comment]
The code changes required for this testing are on the spark-uuid-migration branch. Awaiting review.

**Comment by javier-molina** [comment]
Let's keep it visible while we finish the sprint.
