### ISSUE TITLE
Produce a CLI tool for running pipelines

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#88]
We need to replace the current set of bash scripts in the `scripts` directory with a fit for purpose tool for running pipelines manually or via Jenkins etc.

We need a nice replacement that provides users with a  single command line tool to run with options.
In addition it will need to be configurable for the specific environment:
1) Clustered / Non-clustered
2) HDFS  / Non HDFS
3) Pipeline options
	- supporting sampling
	- availability of other ALA components
		- if lists are installed, integrate
		- if SDS is installed, integrate
		- and more...

**Comment by vjrj** [comment]
I just pushed some more code to simplify the arguments of the classes via a yaml before working in a simplified CLI interface.

See:
https://github.com/vjrj/la-pipelines/blob/yaml-conf/scripts/dwca-avro.sh

and:
https://github.com/vjrj/la-pipelines/blob/yaml-conf/pipelines/src/main/java/au/org/ala/pipelines/beam/DwcaToVerbatimPipeline.java#L28

We can refactor to anything more readable or with other structure:
https://github.com/vjrj/la-pipelines/blob/yaml-conf/pipelines/src/main/resources/la-pipelines.yaml

And the tests:
https://github.com/vjrj/la-pipelines/blob/yaml-conf/pipelines/src/test/java/au/org/ala/utils/CombinedConfigurationTest.java

Comments, welcome.

**Comment by vjrj** [comment]
I forget to mention that I see some problem with this approach while using `PipelineOptions`. If we add some extra option to the yaml (imagine an used variable), PipelinesOptions will fail like this: 
```
./dwca-avro.sh dr893                                
Ingest DwCA - Converts DwCA to verbatim.arvo file.
Exception in thread "main" java.lang.IllegalArgumentException: Class interface 
org.gbif.pipelines.ingest.options.InterpretationPipelineOptions missing a property named 'someUnusedVar'.
```
So I'm not totally happy with the result.

**Comment by vjrj** [comment]
I have some doubts to continue with la-pipelines#88.

We have at least, a pair of scenarios:
1) development: (with different environments to test, like cluster/embedded hdfs/no-hdfs, etc) 
2) production: a more stable environment with a fix configuration, although this configuration can change occasionally over time (to switch from one type of deployment to other, since the first deployment)

With #90 we can have:
1) some testing configurations in yaml that can be merged using the `--config` argument (comma separated). So we can rewrite the set-env scripts with yaml testing configurations for each environment
2) some initial reference yaml configuration, well documented, with basic values and some other values commented cluster/hdfs/species-lists/other-services values, etc). This is the one installed by a future debian packaging system. Also we can tune this reference configuration with a local configuration generated for instance via ansible with the real values for some LA specific deployment like ALA. This is also easy to use via jenkins: we have some yaml production configuration we use on each jenkins tasks with few arguments (command, all/drXXX).

This yaml configuration works well for all the java pipeline options but not for the `spark-submit` shell arguments.

All these yaml values are converted to args with #88 and passed to each `PipelineOptions`.

Now, to simply the number of `scripts` I can imagine two options:
1) Use [docopt](http://docopt.org/) for bash to simplify that scripts [1], this can work for some simple CLI interface.
2) Use [picocli.info](https://picocli.info) in java to generate a more CLI with advanced commands/args per pipeline. The problem I see it's that is quite similar/redundant to `PipelinesOptions`, but we can try to unify both via extra annotations. The other problem with this option is that we have to still maintain the `spark-submit` commands and args in shell.

Both options can be configured to have autocomplete of options and args.

My main doubt is if we need to have all the pipeline arguments visible and configurable in a CLI or with the yaml configuration (better commented) is enough. Because if this is not necessary, we can simplify the CLI and use docopt bash.

I hope is clear.

[1] We already use docopts for our living atlas ansible generator to simplify the use of ansible-playbooks, and allows to deploy the main LA services with a simple command with few args:

```
   ./ansiblew -h
This is an ansible wrapper to help you to exec the different playbooks with your inventories.

Usage:
   ansiblew --alainstall=<dir_of_ala_install_repo> [options] [ main | collectory | ala_hub | biocache_service | ala_bie | bie_index | images | lists | regions | logger | solr | cas | biocache_backend | biocache_cli | spatial | webapi | alerts | doi | nameindexer |  all ]
   ansiblew -h | --help
   ansiblew -v | --version

Options:
  --nodryrun             Exec the ansible-playbook commands
  -p --properties        Only update properties
  -l --limit=<hosts>     Limit to some inventories hosts
  -s --skip=<tags>       Skip tags
  -t --tags=<tags>       Limit to tags
  -h --help              Show help options.
  -d --debug             Show debug info.
  -v --version           Show ansiblew version.
----
ansiblew 0.1.0
Copyright (C) 2019 living-atlases.gbif.org
Apache 2.0 License
```

**Comment by djtfmartin** [comment]
thanks @vjrj 

Im not sure which of the options is better. I think im favouring docopt - perhaps it is has better separation without the need to merge PipelineOptions. Happy to go with either approach though.

**Comment by vjrj** [comment]
I'm start to think in something simple like this that relays in default yaml configurations, but optional configuration/args can also be added to command line:

```bash
$ ./la-pipelines -h   
LA-Pipelines data ingress utility.

Pipeline ingress steps:

    ┌───── do-all ──────────────────────────────────┐
    │                                               │
dwca-avro --> interpret --> uuid -->                │
     export-latlng --> sample --> sample-avro --> index

Usage:
  la-pipelines dwca-avro (<dr>|all)
  la-pipelines interpret (<dr>|all)
  la-pipelines uuid (<dr>|all)
  la-pipelines export-latlng (<dr>|all)
  la-pipelines sample (<dr>|all)
  la-pipelines sample-avro (<dr>|all)
  la-pipelines index (<dr>|all)
  la-pipelines do-all (<dr>|all)

Options:
      --config         Comma separated list of alternative la-pipeline yaml configurations (the last file has the highest precedence)
      --extra-args     Additional "arg1=values,arg2=value" to pass to pipeline options (highest precedence than yml values)
      --no-colors      No corolorize logs output
      -h --help        Show this help
      -v --version     Show version
```

During testing/developing we can use  `--config` or `--extra-args` if we need it, but under normal use `la-pipelines cmd'  should be enough.

Spark, hdfs, etc options can also be provided in the yaml. For that, I was thinking also in using [yq](https://github.com/mikefarah/yq) so we can read `spark-submit` args from bash:

```bash
INTERPRET_NUM_EXECUTORS=$(cat la-pipelines.yaml | yq r - 'interpret-spark.num-executors') 
```

What do you think?

**Comment by djtfmartin** [comment]
+1 from me. This looks useful.

**Comment by vjrj** [comment]
I'm starting to commit here:
https://github.com/gbif/pipelines/compare/ala-dev...vjrj:cli

Including logs for daltonics:
![2020-10-14-10:14:21-screenshot](https://user-images.githubusercontent.com/180085/87403275-f4372680-c5bc-11ea-882a-45c0c4ac9b98.png)

**Comment by vjrj** [comment]
I just pussed [here](https://github.com/gbif/pipelines/compare/ala-dev...vjrj:cli) a first functional version tested in local. The help looks currently like:

```
./la-pipelines -h                                                            
LA-Pipelines data ingress utility.

Pipeline ingress steps:

    ┌───── do-all ──────────────────────────────────┐
    │                                               │
dwca-avro --> interpret --> uuid -->                │
     export-latlng --> sample --> sample-avro --> index

Usage:
  la-pipelines [options] dwca-avro (<dr>|all)
  la-pipelines [options] interpret (<dr>|all) [local|embedded|cluster]
  la-pipelines [options] uuid (<dr>|all) [embedded|cluster]
  la-pipelines [options] export-latlng (<dr>|all) [embedded|cluster]
  la-pipelines [options] sample (<dr>|all)
  la-pipelines [options] sample-avro (<dr>|all) [embedded|cluster]
  la-pipelines [options] index (<dr>|all) [local|embedded|cluster]
  la-pipelines [options] do-all (<dr>|all) [local|embedded|cluster]
  la-pipelines -h | --help
  la-pipelines -v | --version

Options:
  --config=<files>     Comma separated list of alternative la-pipeline yaml configurations (the last file has the highest precedence)
  --extra-args=<args>  Additional "arg1=values,arg2=value" to pass to pipeline options (highest precedence than yml values)
  --no-colors          No corolorize logs output
  -h --help            Show this help
  -v --version         Show version
```
I'm not totally convinced of the `[local|embedded|cluster]` part. For now stills use `set-env` and the JVM and `spark-submit` args are still hardcoded, but we can start to move it outside easily with the cli options more defined. 

The logs looks like:
![2020-09-15-09:08:47-screenshot-cli](https://user-images.githubusercontent.com/180085/87514681-e6e07180-c67a-11ea-81bc-c63edc43968a.png)

**Comment by djtfmartin** [comment]
thanks @vjrj ill take a look

**Comment by vjrj** [comment]
Hi @djtfmartin 

I'm improved the cli a bit more, now with configurable jvm/spark args, and more options like `--dry-run`. If we find a moment to talk about cluster/embedded options, with some refactoring it's almost ready.

I have several problems building `ala-dev` but I see your are working hard to merge it, so I'll wait.

PS: `dataset-counts.csv` is not correct generated. I see the development is a work in progress. Some minor patch I used to make it work:
[dump-data.patch.txt](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/4936278/dump-data.patch.txt)

.

**Comment by vjrj** [comment]
I continued improving this utility. Right now I think can be a good substitute of the current step scripts.

But to finish a more coherent version I have a main doubt. The current version get the args and options is in the `la-pipelines.yaml`.

See the interpret function gets the yaml values and use it in java and spark-submit args:
https://github.com/vjrj/pipelines/blob/cli/livingatlas/scripts/la-pipelines#L234

The reference `la-pipelines.yaml` looks like:

https://github.com/vjrj/pipelines/blob/cli/livingatlas/configs/la-pipelines.yaml
but it still uses the set-env* scripts. 

The help looks like this:
```
LA-Pipelines data ingress utility.

The la-pipelines can be executed to run all the ingress steps or only a few of them:

Pipeline ingress steps:

    ┌───── do-all ──────────────────────────────────┐
    │                                               │
dwca-avro --> interpret --> uuid -->                │
     export-latlng --> sample --> sample-avro --> index

-  'dwca-avro' reads a Dwc-A and converts it to an Avro file;
-  'interpret' reads a Dwc-A, interprets it and write the interpreted data and the issues in Avro files;
-  'uuid' minting on new records and rematching existing UUIDs to records that have been previously loaded;
-  'export-latlng' exports a unique set of coordinates for a dataset into CSV;
-  'sample' crawl the LA layers. Requires an input csv containing lat, lng (no header) and output directory.
-  'sample-avro' adds a sampling AVRO extension to the stored interpretation
-  'index' reads a Dwc-A, interprets it and index the interpeted data creating a SOLR index.

All the steps generate an output. If only the final output is desired, the intermediate outputs can be ignored.

Usage:
  la-pipelines [options] dwca-avro     (<dr>...|all)
  la-pipelines [options] interpret     (<dr>...|all) [--local|--embedded|--cluster]
  la-pipelines [options] uuid          (<dr>...|all)         [--embedded|--cluster]
  la-pipelines [options] export-latlng (<dr>...|all)         [--embedded|--cluster]
  la-pipelines [options] sample        (<dr>...|all)
  la-pipelines [options] sample-avro   (<dr>...|all)         [--embedded|--cluster]
  la-pipelines [options] index         (<dr>...|all) [--local|--embedded|--cluster]
  la-pipelines [options] do-all        (<dr>...|all) [--local|--embedded|--cluster]
  la-pipelines -h | --help
  la-pipelines -v | --version

Options:
  --config=<files>     Comma separated list of alternative la-pipeline yaml configurations (the last file has the highest precedence).
  --extra-args=<args>  Additional "arg1=values,arg2=value" to pass to pipeline options (highest precedence than yml values).
  --no-colors          No corolorize logs output.
  --dry-run            Print the commands without actually running them.
  --debug              Debug la-pipelines.
  -h --help            Show this help.
  -v --version         Show version.
```

I added the ` [--local|--embedded|--cluster]` because I was not totally sure that our initial analysis, that each LA deploy has a unique more or less stable configuration expressed in a yaml, is still valid. 

I can remove these options and to choose the method based on the yaml configuration (with vars like `use_cluster`?). Also I can move the `sen-env` vars to the yaml. In this case, if we want to choose different between local/spark-cluster/spark-embedded  (for instance for development purposes) it should be done using different yml configs, via `--config`.

I can follow any other approach if this doesn't fit to what we are looking for.

**Comment by vjrj** [comment]
Maybe it's better to start using this at the current status, prior to take other decisions like how to simplify the interface, etcetera

**Comment by vjrj** [comment]
I think that the next step to polish a bit more the `la-pipelines` script, is to move the `set-env` variables to the yaml default config. Also I think we can try to move the `configs/la-pipelines-spark-embedded.yaml` etc to a single `configs/la-pipelines.yaml` (I don't think if this will be possible as `PipelineOptions` is quite strict with their args).

In this case, imagine that we have some yaml variable `runOn: cluster`. In this case,  `la-pipelines` will try to run always in the cluster for big drs and it will read all the variables that are necessary to run on a cluster from the yaml. `runOn` (we can choose other name) can be `local`, `embedded`, or `cluster`. 

In the CLI we can force where to run via `[--local|--embedded|--cluster]` but by default, if it's not specified, will use `runOn` configured value.

I don't know if this is enough to the current ALA necessities and if this clarifies the general use. Other options welcome!

**Comment by djtfmartin** [comment]
That sounds good to me @vjrj

**Comment by vjrj** [comment]
Can I start removing the old /scripts/ ? If you aren't still using it...

**Comment by vjrj** [comment]
I just published a `la-pipelines` debian package. Instructions:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Testing-Debian-Packaging#using-demo-repository
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Testing-Debian-Packaging#testing-la-pipelines-package

To use the autocompletion you should open a new session after the installation.

I'll send a PR with this debian package after gbif/pipelines#346 is merged.

**Comment by vjrj** [comment]
Right now, after cleaning a bit old scripts and configs, I see we have to reconsider:
- `scripts/hdfs-ingest.sh` (Probably not necessary now neither)
- `scripts/pipeline.yml` 

@djtfmartin: Any reason against join `configs/la-pipelines.yaml` and `scripts/pipelines.yaml` ? Probably some changes should be done in the AlaPipelinesClasses in order to get the ws configs properly.

**Comment by djtfmartin** [comment]
@vjrj i was thinking of this too. I think it makes sense.

`scripts/hdfs-ingest.sh` can be deleted i think.

**Comment by vjrj** [comment]
Hi @djtfmartin, I worked in this direction:
https://github.com/gbif/pipelines/compare/ala-dev...vjrj:minor88works
trying not to modify the current pipelines options.

I tried before to remove the `properties` option, but I'm not very confident with this part of the code to do it. 

Probably later we can refactor, simplify and improve this part of the code.

My doubt is that now this properties are always local, and I'm not sure if this is ok.

What do you think?

**Comment by vjrj** [comment]
Any feedback/request about this issue? If not, I think we can close it and create new ones.

**Comment by djtfmartin** [comment]
thanks @vjrj I think its working well - thank you. I'll mark as done. The work has been reviewed and merged.

**Comment by javier-molina** [comment]
Thanks @vjrj for your work.
