### ISSUE TITLE
STATE_COORDINATE_MISMATCH logic incorrect

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#92]
The current logic around creating `STATE_COORDINATE_MISMATCH` is simplying checking if the value in `LocationRecord.stateProvince` matches a vocabulary after processing has been performed.

What is required is a check to see of the `stateProvince` value retrieved from lookup up the stateProvince via coordinates matches the stateProvince in the raw data if it has been provided.

**Comment by qifeng-bai** [comment]
We have a state name match file. For example: Australian Capital Territory	AustCapitalTerritory	AustCapitalTerrit	AusCap	AusCapTerrit	ACT	Jervis Bay Territory	Australian Captial Territory.

I am wondering if we also need to identify  'ACT' == "AustCapitalTerritory" for this assertion

**Comment by djtfmartin** [comment]
Yes we should. Good catch.

**Comment by javier-molina** [comment]
@qifeng-bai  gbif/pipelines#328 is still open and there are some concerns on it hence I don't think this should be closed.

Also it seems that we have again multiple features (GH issues) combined into a single PR, my understanding is that we should have separate feature branches per GH issue and separate PR as well in order to avoid falling in the trap of introducing artificial dependencies as we did before. I know it can be a pain to maintain more branches at your end but I think it is worth having every GH issue concern independent. 

My suggestion is to re-issue separate PR but I could be wrong or missing something so happy to talk if you want.
