### ISSUE TITLE
interpret-java throws errors for CentrePoints

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#96]
Running `./interpret-java.sh dr7452` on the spark-1 throws lots of errors like:

```
...
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
20/07/21 21:31:09 [dr7452] 1  ERROR CentrePoints: Australia is not found in records
...
```

**Comment by djtfmartin** [comment]
I think these errors are caused because the names used in the `src/main/resources/countryCentrePoints.txt` do not align with the country names returned by the `GeocodeShpIntersectService`. Ive seen similar errors for the names in `src/main/resources/stateProvinceCentrePoints.txt`.

Suggest we need to fix up the content of `src/main/resources/countryCentrePoints.txt` to match, and it may make sense to use the ISO country code in `countryCentrePoints.txt` instead.

**Comment by qifeng-bai** [comment]
Cannot repeat this issue

**Comment by djtfmartin** [comment]
I believe issue is caused because the loading the vocabulary files is not thread-safe. This is evident in the logs:

<img width="982" alt="Screen Shot 2020-07-23 at 1 29 37 pm" src="https://user-images.githubusercontent.com/444897/88293817-6b726600-ccf3-11ea-9e5d-1ebf8b339e51.png">

Note in particular the different counts for loaded state centres.

**Comment by qifeng-bai** [comment]
@adam-collins @sadeghim 
I find that defining getInstance() method as 'synchronized' solves this issue.

The way of I tested is:
Create 100 treads of initing StateCentrePoints,  print how many states have been loaded. also I added some 500ms delay in each line parsing. 

I found:
Without "synchronized", it printed different size, but after "synchronized" added, it printed 8 states always.

Please let me know your thourghts
