### ISSUE TITLE
Analysis of Habitat Transform

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#97]
- [x] Analyse what is need it to implement the Habitat transform. 
- [ ] Identification of source data to use (i.e. version of IRMNG)
- [ ]  Add breakdown of GH issues for the technical tasks need it

**Comment by javier-molina** [comment]
Currently in biocache store the biome field is populated based on the occurrence record intersection with a terrestrial or marine layer. [LocationProcessor.scala#L72](https://github.com/AtlasOfLivingAustralia/biocache-store/blob/develop/src/main/scala/au/org/ala/biocache/processor/LocationProcessor.scala#L72). IRMNG data is not used at all to populate biome field.

**Comment by djtfmartin** [comment]
As @javier-molina says, in biocache-store, the `biome` field is populated by intersecting coordinates with values from a terrestrial or marine layer. Currently, in production we are using the IBRA layer for terrestrial and IMCRA layer for marine. These layers where chosen at the time (a long time ago) because they had a higher resolution compared to others available in ALA.  If the point intersections a polygon in IBRA, then `biome= terrestrial`, If the point intersection a polygon in IMCRA `biome= marine`. This is obviously very coarse, doesn't handle other habitat types (e.g. freshwater), but this is the current state of play in biocache-store. I'm sure we can do better than this, but we need to identify data sources to support it.

In biocache-store, IRMNG data is used to retrieve the Marine/Non-marine status of the taxon associated with the occurrence record. This is done with the sole intention of cross checking the derived `biome` value. If a taxon is marked as Marine in IRMNG and the coordinates are Terrestrial then an HABITAT_MISMATCH issue is raised.

As we took the decision to drop support for `HABITAT_MISMATCH` issue flagging, we no longer need to make use of IRMNG.

**Comment by RobinaSanderson** [comment]
From email from Sebastien Mancini:
No, the AODN is not querying the ALA API at the moment. It would be great to revisit the data flows between the ALA and AODN at some stage but the next couple of months are already very busy with a few projects going on ...

**Comment by djtfmartin** [comment]
thanks @RobinaSanderson 

With this in mind, and given the uncertainty around use of IRMNG etc, i suggest we deprecate `species_habitats` field. Support can always be added back in a later release of pipelines.

**Comment by peggynewman** [comment]
OBIS AU uses this query to find marine datasets: 

https://biocache.ala.org.au/ws/occurrences/search?q=species_habitats:Marine&facets=data_resource_id&pageSize=0&flimit=1000 

so not sure whether we should deprecate `species_habitats`

**Comment by peggynewman** [comment]
I think there might be a solution here whereby we can either use IRMING or WoRMS to identify marine species. We are soon to integrate WoRMS into the names index, awaiting contract approvals etc. I think this issue should be revisited by the project reference group.

**Comment by javier-molina** [comment]
`biome` field has already been implemented as part of https://github.com/gbif/pipelines/pull/485
